export { default as LoginScreen } from './Login/Login.jsx';
export { default as RegisterScreen } from './Register/Register.jsx';
export { default as HomeScreen } from './Home/Home.jsx';
export { default as LoadingScreen } from './Loading/Loading.jsx';
export { default as QuizScreen } from './Quiz/Quiz.jsx';
export { default as HomeTeacherScreen } from './HomeTeacher/HomeTeacher.jsx';
export { default as SettingsTournamentScreen } from './SettingTournament/SettingTournament.jsx';
export { default as LobbyScreen } from './Lobby/LobbyScreen.jsx';
export { default as GameTournamentScreen } from './GameTournament/GameTournament.jsx';